version: '3'
services:
  app:
    image: Grocery-server:latest
    environment:
      - CONNECTION_URL =  // Add your MONGO_URL    
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE= GrocerySystem
    ports:
      - '27018:27017'